// Based on tools/version.h.in

#ifndef NOTCURSES_VERSION_HEADER
#define NOTCURSES_VERSION_HEADER

#define NOTCURSES_VERNUM_MAJOR _MESON_NOTCURSES_VERNUM_MAJOR
#define NOTCURSES_VERNUM_MINOR _MESON_NOTCURSES_VERNUM_MINOR
#define NOTCURSES_VERNUM_PATCH _MESON_NOTCURSES_VERNUM_PATCH
#define NOTCURSES_VERNUM_TWEAK _MESON_NOTCURSES_VERNUM_TWEAK

#define NOTCURSES_VERSION_COMPARABLE(major, minor, patch) \
  (((major) << 16u) + ((minor) << 8u) + (patch))

#define NOTCURSES_VERNUM_ORDERED NOTCURSES_VERSION_COMPARABLE( \
  NOTCURSES_VERNUM_MAJOR, NOTCURSES_VERNUM_MINOR, NOTCURSES_VERNUM_PATCH)

#define _STRINGIZE_NX(A) #A
// Converting numbers to string literals
#define _STRINGIZE(A) _STRINGIZE_NX(A)

#define NOTCURSES_VERSION_MAJOR _STRINGIZE(NOTCURSES_VERNUM_MAJOR)
#define NOTCURSES_VERSION_MINOR _STRINGIZE(NOTCURSES_VERNUM_MINOR)
#define NOTCURSES_VERSION_PATCH _STRINGIZE(NOTCURSES_VERNUM_PATCH)
#define NOTCURSES_VERSION_TWEAK _STRINGIZE(NOTCURSES_VERNUM_TWEAK)

#endif